
# My original approach:
# dna = input("Find reverse complement of the following sequence:")
dna = "TTTTATCAATACTCCAGGGTACCCTTCCTCAAGTCCCTAGCGTTGCCGGCCTAACTTGAACATAATTCAGACGTGGACCCAACTTACAGAGTACAGCAGGTACATAACCCTCGCGCGGCTCTAACAATACTTTCGATTTTGCAACTGTCCCCTCAACGCACTATGTTTGGCGCTCCCAGGAGAGTAGTGCCGACCGTCGGCTGCAAACTTTGGCATATCCTAGAGATCTTGCCCAGGGGCCATTGACTTCGACGATAACCATTATATCACCGATAATTATCCTGTATGGTAGGTGAGCGTTTGAAGTTTTCTACACTTGAATATTGGGAGTCGTATTCGTCTCACATCCGGTGGCGCCTTGTCCCCCCATGACACGATACTAATTGACTTCTTGAAGGAGTGGGCAGCAGGGGGACTATGCGCTTCGGTGCTCTCATGATCTGCAATGGAGCAGATGACCCCAGTTTCTTAACTGCATCTCTTAACGCGTCTCTTCGCTTGGATCGAGCTATCTGCACTAAGCCTGGCGCTATAAGTCGCTTCAGCTAGCAATGTGAATCAGGGAGGAAAATAAGTAAGGGTCGTACCGTATTCACCTGCTAAGAGTTACTTAGAGGAAGAAAAGGGCGAAACTTCGGACAGCTTACATGACAGCGCGCTAGTTGGCTAGGGGGTAACCTGTCAGCATCGAACTCGCTGCCGGAAACAAGGGTCCGCGGCTCTAAATTCGCGCTACACTGTCGGTGTTTGCCCTGCTCCGGGCTAGATTCAAATTACCAACTACAAAGAGTACGTTCGACCGAATATCGGTCGGATCCACTGGGGTCGGCTAATATGGTCCCGGCGTCACGATAAACCACCTT"

dna = list(dna)
dna.reverse()
rev_dna = dna

base_pairing = {"A":"T", "T": "A", "C": "G", "G": "C"}

comp_rev_dna = []
for nucleotide in rev_dna:
    nucleotide = base_pairing[nucleotide]
    comp_rev_dna.append(nucleotide)

print("".join(comp_rev_dna))


## Communitiy approaches: 4 x .replace in one row